# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrendingNewsML' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrendingNewsML
  pod 'SwiftLint'
  pod 'ReadabilityKit'

end

target 'TrendingNewsMLUnitTests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrendingNewsML
  pod 'ReadabilityKit'

end

target 'TrendingNewsMLGNewsUnitTests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrendingNewsML
  pod 'ReadabilityKit'

end

target 'TrendingNewsMLUITests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrendingNewsML
  pod 'ReadabilityKit'

end

